name: learn-gcp-auth
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  deploy:
    environment: 'PROD'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SA }}'
